In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
from sklearn import metrics
import warnings 
warnings.filterwarnings('ignore')

In [2]:
d_t = pd.read_csv('train.csv')

In [3]:
df = d_t.replace(np.nan, 0)

In [4]:
df.head(6)
#df.tail(5)

Id Location    Cases  Year  Deaths  Mortality  Total Vaccinations  \
0  911530868    World   2372.0  2020    65.0      0.008                 0.0   
1  807936902    World   5023.0  2020   114.0      0.014                 0.0   
2  773590408    World   5612.0  2020   116.0      0.015                 0.0   
3  130466459    World   7580.0  2020   153.0      0.019                 0.0   
4  544040446    World   8983.0  2020   187.0      0.024                 0.0   
5  112222711    World  10601.0  2020   217.0      0.027                 0.0   

   Vaccinated   Fully Vaccinated  
0         0.0                0.0  
1         0.0                0.0  
2         0.0                0.0  
3         0.0                0.0  
4         0.0                0.0  
5         0.0                0.0

In [5]:
df.shape

(129156, 9)

In [6]:
print(df.dtypes)

Id                      int64
Location               object
Cases                 float64
Year                    int64
Deaths                float64
Mortality             float64
Total Vaccinations    float64
Vaccinated            float64
 Fully Vaccinated     float64
dtype: object


In [7]:
#df['Cases per Million'].value_counts()[0.0]

In [8]:
#df[' Fully Vaccinated'].

In [9]:
# create a list of column names to check for 0.0 values
cols_to_check = ['Vaccinated', ' Fully Vaccinated', 'Total Vaccinations']

# select the rows where any of the columns has a value of 0.0
rows_to_delete = df[df[cols_to_check].isin([0.0])].dropna(how='all').index

# drop the selected rows from the DataFrame
df = df.drop(rows_to_delete)


In [10]:
def round_decimal(x):
    decimal_part = x - int(x)
    if decimal_part > 0.5:
        return int(x) + 1
    else:
        return int(x)

# apply the lambda function to the 'my_column' column
df['Deaths'] = df['Deaths'].apply(lambda x: round_decimal(x))
df['Mortality'] = df['Mortality'].apply(lambda x: round_decimal(x))
df['Total Vaccinations'] = df['Total Vaccinations'].apply(lambda x: round_decimal(x))
df['Vaccinated'] = df['Vaccinated'].apply(lambda x: round_decimal(x))
df[' Fully Vaccinated'] = df[' Fully Vaccinated'].apply(lambda x: round_decimal(x))
df['Cases'] = df['Cases'].apply(lambda x: round_decimal(x))


In [11]:
df

Id  Location    Cases  Year  Deaths  Mortality  \
231     888927956     World  4401227  2020   78095         10   
232     692158819     World  4417781  2020   78496         10   
233     235232640     World  4487887  2020   80910         10   
234     915746346     World  4554209  2020   81609         10   
235     805449786     World  4555265  2020   81866         10   
...           ...       ...      ...   ...     ...        ...   
129149  737286942  Zimbabwe      554  2022      15          1   
129151  541829605  Zimbabwe      464  2022      13          1   
129152  969939474  Zimbabwe      471  2022      12          1   
129154  961193720  Zimbabwe      277  2022       6          0   
129155  832612563  Zimbabwe      277  2022       6          0   

        Total Vaccinations  Vaccinated   Fully Vaccinated  
231                  35647       29152               7425  
232                  40330       33668               7565  
233                1779065      266515               8318  
234                2057367      538177               9091  
235                2664507     1132176              11428  
...                    ...         ...                ...  
129149            11945534     6296280            4599476  
129151            11949993     6297324            4601845  
129152            11958771     6299348            4605821  
129154            11974313     6305470            4611113  
129155            11984914     6310089            4614738  

[35220 rows x 9 columns]

In [12]:
x = df[['Cases','Deaths','Total Vaccinations','Vaccinated',' Fully Vaccinated']]
x.shape

(35220, 5)

In [13]:
y = df[['Mortality']]
shape = y.shape
shape

(35220, 1)

In [14]:
x_a=np.array(x)
y_b=np.array(y)
x_a.shape

(35220, 5)

In [15]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x_a,y_b, test_size = 0.2, random_state=42)

In [16]:
x_test.shape
#y_test.shape

(7044, 5)

In [17]:
# from sklearn.ensemble import RandomForestClassifier
# #from sklearn.ensemble import RandomForestRegressor
# #from sklearn.tree import DecisionTreeClassifier
# #from sklearn.tree import DecisionTreeRegressor
# #from sklearn.linear_model import LogisticRegression
# #from sklearn.linear_model import LinearRegression
# #from sklearn.svm import SVC
# #from sklearn.svm import SVR
# #from xgboost import XGBRegressor
# #from xgboost import XGBClassifier
# #from sklearn.ensemble import AdaBoostClassifier
# #from sklearn.ensemble import GradientBoostingRegressor
# #from sklearn.ensemble import GradientBoostingClassifier
# #from sklearn.neighbors import KNeighborsRegressor
# #from sklearn.cluster import KMeans  
# from sklearn.model_selection import GridSearchCV

In [18]:
# forest= RandomForestClassifier()
# # param_grid = {
# #     'n_neighbors': [3, 5, 7],
# #     'weights': ['uniform', 'distance'],
# #     'metric': ['euclidean', 'manhattan']
# # }
# # forest = GridSearchCV(forest, param_grid, cv=5, scoring='accuracy')
# # forest = KMeans(n_clusters=4, random_state= 42)  

# forest.fit(x_train,y_train)



In [19]:
# from sklearn.model_selection import GridSearchCV
# from sklearn.ensemble import RandomForestClassifier

# # Create a random forest classifier
# forest = RandomForestClassifier(random_state=42)

# # Define the hyperparameters to be tuned and their possible values
# param_grid = {
#     'n_estimators': [50, 100, 150],
#     'max_depth': [10, 20, 30],
#     'min_samples_split': [2, 5, 10],
#     'min_samples_leaf': [1, 2, 4]
# }

# # Create a grid search object
# forest = GridSearchCV(forest, param_grid, cv=5, n_jobs=-1)

# # Fit the grid search object to the data
# forest.fit(x_train, y_train)

In [20]:
# from sklearn.ensemble import RandomForestClassifier, VotingClassifier
# from sklearn.metrics import accuracy_score
# rfc1 = RandomForestClassifier(n_estimators=100, max_depth=5, random_state=42)
# rfc2 = RandomForestClassifier(n_estimators=50, max_depth=3, random_state=42)
# rfc3 = RandomForestClassifier(n_estimators=200, max_depth=7, random_state=42)
# forest = VotingClassifier(estimators=[('rfc1', rfc1), ('rfc2', rfc2), ('rfc3', rfc3)], voting='hard')

In [21]:
# forest.fit(x_train, y_train)
# y_pred = forest.predict(x_test)
# accuracy = accuracy_score(y_test, y_pred)
# print("Accuracy:", accuracy)

Accuracy: 0.24630891538898353


In [22]:

print("TRAIN  accuracy_score:", forest.score(x_train,y_train)*100)

TRAIN  accuracy_score: 24.190800681431003


In [23]:
y_pred = forest.predict(x_test)
print(y_pred)
#x_test.shape

[2 0 0 ... 1 2 2]


In [24]:
print("TEST accuracy_score:", accuracy_score(y_pred,y_test)*100)

TEST accuracy_score: 24.630891538898354


In [25]:
# # from sklearn.metrics import mean_squared_error

# y_pred = forest.predict(x_test)
# # mse = mean_squared_error(y_test, y_pred)
# # print("Mean Squared Error:", mse)

In [26]:
from sklearn.metrics import confusion_matrix
cf_matrix = confusion_matrix(y_pred,y_test)
print(cf_matrix)

[[1134  136   73 ...    0    0    1]
 [  66  360  201 ...    1    1    0]
 [  38  101  232 ...    0    0    0]
 ...
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]]


In [27]:
from sklearn.metrics import classification_report
cls_rp =(classification_report(y_test,y_pred)*100)
print(cls_rp)

              precision    recall  f1-score   support

           0       0.63      0.92      0.75      1238
           1       0.18      0.60      0.28       597
           2       0.07      0.46      0.12       506
           3       0.00      0.00      0.00       335
           4       0.00      0.00      0.00       275
           5       0.00      0.00      0.00       249
           6       0.00      0.00      0.00       265
           7       0.00      0.00      0.00       199
           8       0.00      0.00      0.00       193
           9       0.50      0.04      0.07       195
          10       1.00      0.01      0.03       148
          11       0.00      0.00      0.00       135
          12       0.00      0.00      0.00       131
          13       0.00      0.00      0.00       135
          14       0.00      0.00      0.00       100
          15       0.00      0.00      0.00       114
          16       0.00      0.00      0.00       111
          17       0.00    